# Generated by Django 4.2.15 on 2024-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0003_alter_ordentrabajo_tipopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='esAbono',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es Abono'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='esPagoTotal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es Pago Total'),
        ),
    ]
