# Generated by Django 4.2.15 on 2024-11-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0004_ordentrabajo_esabono_ordentrabajo_espagototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='estadoDelPago',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado del Pago'),
        ),
    ]
