# Generated by Django 4.2.15 on 2024-11-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0006_alter_ordentrabajo_estadodelpago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abono',
            old_name='formaPagoAbono',
            new_name='tipoPagoAbono',
        ),
        migrations.AlterField(
            model_name='abono',
            name='idAbono',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Abono'),
        ),
    ]
