# Generated by Django 4.2.15 on 2024-11-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0007_rename_formapagoabono_abono_tipopagoabono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='estadoOrdenTrabajo',
            field=models.CharField(default=11, max_length=20, verbose_name='Estado Orden de Trabajo'),
            preserve_default=False,
        ),
    ]
