# Generated by Django 4.2.15 on 2024-11-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0011_remove_abono_rutadministrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='rutAdministrador',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='rutAtendedor',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='rutTecnico',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='rutAdministrador',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='rutAtendedor',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='rutTecnico',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='rutAdministrador',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='rutAtendedor',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='rutTecnico',
        ),
    ]
