# Generated by Django 4.2.15 on 2024-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0014_abono_saldoanterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='idCertificado',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='rutCliente',
        ),
        migrations.AddField(
            model_name='certificado',
            name='numeroCertificado',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID Certificado'),
            preserve_default=False,
        ),
    ]
